apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2017-10-16T04:44:01Z
  generation: 3
  labels:
    run: extractor-worker
  name: extractor-worker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: extractor-worker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: extractor-worker
    spec:
      containers:
      - image: extractor-token-receiver:latest
        imagePullPolicy: IfNotPresent
        name: extractor-token-receiver
        command:
          - "/usr/local/bin/rq"
        args:
          - "worker"
#          - "--burst"
          - "-c"
          - "token-queue-settings"
        env:
        - name: SECRET_BNZ_TOKEN
          valueFrom:
            secretKeyRef:
              name: bnz
              key: token
        volumeMounts:
        - mountPath: "/root/.minikube"
          name: kubernetes-data
        - mountPath: "/root/.kube"
          name: kubernetes-data
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 5
      volumes:
      - configMap:
          name: k8s
        name: kubernetes-data
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-10-20T08:03:20Z
    lastUpdateTime: 2017-10-20T08:03:20Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1